<a class="sr-only" href="#content">Skip navigation</a>

<div class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="index.php"><img src="images/logo1.png" alt="InSystive"></a>
  </div>
  <nav class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><a href="centris_project.php">CentrIS Project</a></li>
      <li><a href="centris_team.php">CentrIS Team</a></li>
      <li><a href="centris_partners.php">CentrIS Partners</a></li>
      <li><a href="centris_sprint.php">Sprint Accelerator</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="about.php">About Us</a></li>
    </ul>
  </nav>
</div>